export default {
  name: 'product',
  title: 'Produit',
  type: 'document',
  groups: [
    { name: 'identity', title: 'Identité' },
    { name: 'details', title: 'Détails' },
    { name: 'commerce', title: 'Commerce' },
  ],
  fields: [
    {
      name: 'name',
      title: 'Nom du produit',
      type: 'string',
      group: 'identity',
      validation: Rule => Rule.required(),
    },
    {
      name: 'brand',
      title: 'Marque',
      type: 'reference',
      to: [{ type: 'brand' }],
      group: 'identity',
      validation: Rule => Rule.required(),
    },
    {
      name: 'designer',
      title: 'Designer',
      type: 'string',
      group: 'identity',
    },
    {
      name: 'year',
      title: 'Année de création',
      type: 'number',
      group: 'identity',
    },
    {
      name: 'category',
      title: 'Catégorie',
      type: 'string',
      group: 'identity',
      options: {
        list: [
          { title: 'Assises', value: 'assises' },
          { title: 'Tables', value: 'tables' },
          { title: 'Luminaires', value: 'luminaires' },
          { title: 'Rangements', value: 'rangements' },
          { title: 'Objets', value: 'objets' },
          { title: 'Extérieur', value: 'exterieur' },
        ],
        layout: 'radio',
      },
      validation: Rule => Rule.required(),
    },
    {
      name: 'subcategory',
      title: 'Sous-catégorie',
      type: 'string',
      group: 'identity',
    },
    {
      name: 'image',
      title: 'Image principale',
      type: 'image',
      group: 'identity',
      options: { hotspot: true },
    },
    {
      name: 'imageUrl',
      title: 'URL image (migration temporaire)',
      description: 'Utilisé lors de l\'import initial. Remplacer par une vraie image ci-dessus.',
      type: 'url',
      group: 'identity',
    },
    {
      name: 'gallery',
      title: 'Galerie',
      type: 'array',
      group: 'identity',
      of: [{ type: 'image', options: { hotspot: true } }],
    },
    {
      name: 'description',
      title: 'Description',
      type: 'text',
      rows: 4,
      group: 'details',
      validation: Rule => Rule.required(),
    },
    {
      name: 'material',
      title: 'Matières',
      type: 'string',
      group: 'details',
    },
    {
      name: 'dimensions',
      title: 'Dimensions',
      type: 'string',
      group: 'details',
    },
    {
      name: 'leadTime',
      title: 'Délai de livraison',
      type: 'string',
      group: 'details',
      placeholder: 'ex: 8–10 semaines',
    },
    {
      name: 'price',
      title: 'Prix (€, hors TVA)',
      type: 'number',
      group: 'commerce',
      validation: Rule => Rule.required().positive(),
    },
    {
      name: 'badge',
      title: 'Badge',
      type: 'string',
      group: 'commerce',
      options: {
        list: [
          { title: 'Aucun', value: '' },
          { title: 'Nouveau', value: 'nouveau' },
          { title: 'Limité', value: 'limité' },
          { title: 'Bestseller', value: 'bestseller' },
        ],
        layout: 'radio',
      },
    },
    {
      name: 'available',
      title: 'Disponible',
      type: 'boolean',
      group: 'commerce',
      initialValue: true,
    },
    {
      name: 'featured',
      title: 'Mis en avant',
      type: 'boolean',
      group: 'commerce',
      initialValue: false,
    },
  ],
  preview: {
    select: { title: 'name', subtitle: 'brand', media: 'image' },
    prepare({ title, subtitle, media }) {
      return { title, subtitle, media };
    },
  },
  orderings: [
    { title: 'Nom A–Z', name: 'nameAsc', by: [{ field: 'name', direction: 'asc' }] },
    { title: 'Prix croissant', name: 'priceAsc', by: [{ field: 'price', direction: 'asc' }] },
    { title: 'Prix décroissant', name: 'priceDesc', by: [{ field: 'price', direction: 'desc' }] },
  ],
};
